### ISSUE TITLE
compilation error 

### ISSUE THREAD

**Issue by zhengsongyue** [derectus/File-Converter-Tool#1]
Thanks for your contribution. but 
there are so many syntax error and undeclared variables been used in code. I am wondering if you have uploaded a wrong version or something. if you have time, maybe you can have a check.

**Comment by ncilengir** [comment]
I check again. There is no syntax error or undeclared variables. If u use linux check some libraries in your system like that libjson and libxml2 -links at below-. 

Then; 
You must include libraries when build script like that.
gcc <input_file.c> -I/usr/include/libxml2 -I/usr/include/json-c  -std=c99 -o <output_file> -ljson-c -lxml2

Also if you should add +x permission your output file 
chmod +x ./<output_file>

After all it run without any problems. Thx for feedback \m/


## Requirements
[libjson-c](https://www.archlinux.org/packages/core/x86_64/json-c/)
[libxml2](https://www.archlinux.org/packages/extra/x86_64/libxml2/)
